### ISSUE TITLE
Update headers and footers on all user and developer pages

### ISSUE THREAD

**Issue by Jenelle-SEO** [GeniusButter/genius#21]
Please update all the headers and footers so they match the attached page.  Please make this change on all the User and Developer pages.  If you don't have the Genius Butter Project Logo use the Gold/Yellow Genius Butter one instead.
Thanks!

![3555](https://cloud.githubusercontent.com/assets/11540871/6856264/3b9f4370-d3d5-11e4-98db-66e6e5dee963.jpg)

**Comment by egortimofeev** [comment]
okay. will be pushed today

**Comment by egortimofeev** [comment]
Jenelle, I do not have those images, can you please send it to me. Meanwhile we sill start updating it.

**Comment by Jenelle-SEO** [comment]
Hey Egor,

Can you pull the images from the html files that Rusty provided to you?  (I'm away from my computer right now).

Jenelle

**Comment by egortimofeev** [comment]
Still have some images missed, rusty, could you provide tgis graphics to me? Thank you!

**Comment by Jenelle-SEO** [comment]
![3392](https://cloud.githubusercontent.com/assets/11540871/6902722/7e59097e-d6e3-11e4-9185-00ed3baa6b1a.png)
