### ISSUE TITLE
Site Map Due

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#26]
Rusty to provide a site map that outlines all pages of the site, percentage of completion, where the page resides (ClickFunnel or the website)

**Comment by Jenelle-SEO** [comment]
Find the documents in email

**Comment by rugly** [comment]
I've never seen this document in email - was I just not on that thread?  If this isn't done, please re-open it.

**Comment by seobrand** [comment]
I will email this document out again today - you cannot attack word or pdf docs to these threads, so I can't include it here.
