### ISSUE TITLE
Transfer genius repo to GB organization 

### ISSUE THREAD

**Issue by jpmalek** [GeniusButter/genius#30]
@egortimofeev , we'd like to have the repo transferred to the Genius Butter github org.  I've sent you invites to the teams in that org and gave you admin permissions, so once you accept those invites, per their docs (https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization) you should be able to transfer it at this point on your own.

**Comment by egortimofeev** [comment]
moved
