### ISSUE TITLE
Implement HTML into PHP page

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#32]
Take the sliced HTML and implement the look and feel into the PHP framework so the page displays properly within the site

**Comment by egortimofeev** [comment]
done. just clarify issues with navigation because right now it is not clear how we need to get from one page to another.

**Comment by Jenelle-SEO** [comment]
Egor,

Please see  notable for header navigation

On Thu, Apr 30, 2015 at 2:04 PM, Egor Timofeev <notifications@github.com>
wrote:

> done. just clarify issues with navigation because right now it is not
> clear how we need to get from one page to another.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeniusButter/genius/issues/32#issuecomment-97900063>.
>



-- 
Jenelle Ford
Skype: Jenelle_SEO
