### ISSUE TITLE
Wire up Apps to triggers and actions

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#33]
Wire the app drop downs of the Triggers and actions section to pull form the DB of defined applications

![triggers_and_actions](https://cloud.githubusercontent.com/assets/6989251/7187630/e0486210-e43f-11e4-9e38-9ad93e394ccd.png)

**Comment by egortimofeev** [comment]
done.
right now we have only one trigger. "new item". if you need other triggers let me know so we can develop it.
