### ISSUE TITLE
Test Connection

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#37]
ensure that the connection the user has created works properly

![test](https://cloud.githubusercontent.com/assets/6989251/7187752/d7d67184-e440-11e4-84f8-77eff50b5761.png)

**Comment by egortimofeev** [comment]
what exactly we need to do when we click this button?

**Comment by Jenelle-SEO** [comment]
The test will ping both apps to make sure they are working and connected

**Comment by egortimofeev** [comment]
Jenelle, when you click save it will ping second application we have specified in this screen and will verify first application. Test connection on this screen doesn;t make much sense and just creats some additional development problems on out side. Please confirm you need to have it and we will think how to apply it.
Main issue is we need to poll both applications and to be able to do it we need to create all application structure in our database.. Right now we can do it only when we save it.

**Comment by Jenelle-SEO** [comment]
Ok.  Please remove that section from the design if you're confident the test is happening at the "save"

**Comment by egortimofeev** [comment]
done
