### ISSUE TITLE
Allow the user to Upgrade their Account

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#39]
there is a link that allows the user to upgrade their account on the Connection screen.  If the user selects this link, they should be prompted to save the work they've done and then taken to click funnel where they can upgrade their account

![nameit](https://cloud.githubusercontent.com/assets/6989251/7187807/52987ca0-e441-11e4-9c1d-da5ac0feeff6.png)

**Comment by egortimofeev** [comment]
can you please provide the link we need to open?

**Comment by Jenelle-SEO** [comment]
https://geniusbutter.clickfunnels.com/pricing1
