### ISSUE TITLE
Configure Buttons - test

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#44]
this button should run the test that shows that the configured connection is working

![connectbuttons](https://cloud.githubusercontent.com/assets/6989251/7188024/cb8b18a6-e442-11e4-9c8c-6d3ed2d80b18.png)

**Comment by egortimofeev** [comment]
if application is linked and you have it in this list - we got the token and it will work. so not quite sure why do we need this button.

**Comment by Jenelle-SEO** [comment]
Please remove the test button.  Leaving the others with the edits already provided

**Comment by egortimofeev** [comment]
done
