### ISSUE TITLE
Wire list of available apps to DB

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#49]
ensure that the box of available apps correctly displays the apps that have been configured  based on the DB

![connectionsbox](https://cloud.githubusercontent.com/assets/6989251/7188225/303cc85c-e444-11e4-9284-138e2f7d6342.png)

**Comment by egortimofeev** [comment]
should we show app templates? or user apps? it is not quite clear how this screen needs to work.
right now you can find this screen on user's page.
