### ISSUE TITLE
Enable search bar on available apps

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#50]
make sure the search feature works

![appsearch](https://cloud.githubusercontent.com/assets/6989251/7188263/6475d0fa-e444-11e4-82e5-f093a97e53d9.png)

**Comment by egortimofeev** [comment]
what  it needs to look for? user application/functions? can we define some flow for that?

**Comment by Jenelle-SEO** [comment]
This bar will search for available applications
