### ISSUE TITLE
Create Document Repository

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#55]
we need a location for all technical documents - this can either be in GitHib or in Google docs - unless another system is preferred

**Comment by Jenelle-SEO** [comment]
Errors connecting
https://geniusbutter.atlassian.net/

**Comment by jpmalek** [comment]
Fixed, try : https://geniusbutter.atlassian.net/wiki/display/GEN/GeniusButter+Home

**Comment by Jenelle-SEO** [comment]
It's requiring a login

**Comment by jpmalek** [comment]
Right,  you should be able to create an account and get access using your
seobrand email address.

**Comment by seobrand** [comment]
this is what I get when I try...
![2015-04-30_1917](https://cloud.githubusercontent.com/assets/6989251/7424312/a367811c-ef6d-11e4-889d-1157766741c8.png)

**Comment by jpmalek** [comment]
Try again, please.  I'd put in the seobrand.com domain mistakenly.
