### ISSUE TITLE
ClickFunnel - Can the platform handle subscription cancellations and changes

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#61]
rusty to confirm how if at all ClickFunel deals with recurring subscription cancellations

**Comment by jpmalek** [comment]
I'm not clear on this one - more detail, why, etc?

**Comment by Jenelle-SEO** [comment]
Jeff - as discussed if a user wants to cancel the account there is no way that we've found to do this through clickfunnel/stripe.  
Clickfunnel is not really designed to operate in this manner so we are are researching possible work arounds to this but at this point cancellations will have to be done manually.

**Comment by Jenelle-SEO** [comment]
Rusty is researching if this can be done via he API outside of clickfunnel - it can not happen in clickfunnel

**Comment by Jenelle-SEO** [comment]
All cancellations will have to take place outside of clickfunnel - manually through stripe
