### ISSUE TITLE
User Setting Page Edits

### ISSUE THREAD

**Issue by Jenelle-SEO** [GeniusButter/genius#63]
Please see the following notable for edits to the page and navigation

https://notableapp.com/posts/eaca8c17bc053f356133d95c403b994ae217e720

**Comment by egortimofeev** [comment]
Jenelle, what is my connections link here?
Also right now connected applications and connect new application is the same page. To be able to connect new app on connected page you need to click on dropdown and select application you want to connect.
Please advice.

**Comment by Jenelle-SEO** [comment]
The My Connections page is coming today
