### ISSUE TITLE
Add Developers agreement to site

### ISSUE THREAD

**Issue by Jenelle-SEO** [GeniusButter/genius#66]
Please add  the developers agreement section that I emailed you.

**Comment by egortimofeev** [comment]
Jenelle you sent me notable where you told please replac text with one attached to the issue.. which issue?

**Comment by Jenelle-SEO** [comment]
HI Egor - it would be issue #66.  We need to replace the lorem text with
the real text attached.  (The developers agreement in the developer sign up
process)

On Wed, May 6, 2015 at 8:34 AM, Egor Timofeev <notifications@github.com>
wrote:

> Jenelle you sent me notable where you told please replac text with one
> attached to the issue.. which issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeniusButter/genius/issues/66#issuecomment-99432163>.
>



-- 
Jenelle Ford
Skype: Jenelle_SEO

**Comment by Jenelle-SEO** [comment]
Egor  I emailed you the word document on the 5th

**Comment by Jenelle-SEO** [comment]
Bumping this back to you Egor
